name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Build
        run: npm run-script build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: _dist